/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#123b1b",
        "secondary": "#006e28",
        "on-tertiary-container": "#aebad0",
        "on-secondary-fixed": "#002107",
        "on-primary-fixed-variant": "#274f2d",
        "surface-tint": "#3f6743",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fcf9f8",
        "surface-container": "#f0edec",
        "on-tertiary-fixed": "#111c2c",
        "primary-container": "#2a5230",
        "outline-variant": "#c2c9be",
        "surface": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#53e16f",
        "on-surface": "#1c1b1b",
        "primary-fixed-dim": "#a5d2a6",
        "on-secondary-container": "#00732a",
        "tertiary-fixed": "#d8e3fa",
        "secondary-container": "#6ffb85",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed-dim": "#bcc7dd",
        "inverse-surface": "#313030",
        "outline": "#727970",
        "surface-dim": "#dcd9d9",
        "error": "#ba1a1a",
        "primary-fixed": "#c0eec0",
        "secondary-fixed": "#72fe88",
        "on-background": "#1c1b1b",
        "tertiary-container": "#3f4a5d",
        "on-primary-fixed": "#002108",
        "surface-variant": "#e5e2e1",
        "inverse-primary": "#a5d2a6",
        "surface-container-high": "#ebe7e7",
        "surface-container-low": "#f6f3f2",
        "inverse-on-surface": "#f3f0ef",
        "background": "#fcf9f8",
        "tertiary": "#293345",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-surface-variant": "#424941",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#00531c",
        "on-primary-container": "#97c499",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        // Keeping some old colors for compatibility if needed
        "mint": "#D1FAE5",
        "mint-strong": "#10B981",
        "slate-deep": "#0F172A",
        "blue-accent": "#3B82F6",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "label-bold": ["Work Sans", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "Sora", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "Manrope", "sans-serif"],
        "label": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        sans: ["Plus Jakarta Sans", "Inter", "Arial", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-bold": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}